title: "AHA Research Portfolio"
description: "Researcher profile with papers, projects, and more"
baseurl: ""
url: "https://aha-251226.github.io"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
